apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newTag: 391952492c6af4ae3351698fef48ca15c344e0dc
  newName: emmsys/hello-gitops
